server:
  port: 8222

spring:
  application:
    name: securecapita
  datasource:
    url: jdbc:mysql://learning01.c38kwkm8ixys.ap-south-1.rds.amazonaws.com:3306/securecapital
    username: root
    password: Mo9871682353
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: satyam.dhasmana@gmail.com
    password: elgd ywop vwbs omzp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true